POST {{$dotenv %url}}/token HTTP/1.1
Content-Type: application/json

{
  "Email": "test4@gm.ua"
}

###
POST {{$dotenv %url}}/register HTTP/1.1
Content-Type: application/json

{
  "Username": "test_2",
  "Email": "test4@gm.ua",
  "FirstName": "Test2",
  "LastName": "3",
  "Phone": "+38000000002"
}

###

GET {{$dotenv %url}}/api/workouts HTTP/1.1
Authorization: Bearer {{$dotenv %token}}
